// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/32739/LF/LF-InConcReTeS/fed-gen/inverted_pendulum/src/federate__a.lf
#define LOG_LEVEL 3

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "include/core/federated/federate.h"
#include "include/core/federated/network/net_common.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true", "-o", "1", "sec" };
void lf_set_default_command_line_options() {
        default_argc = 6;
        default_argv = _lf_default_argv;
}
#include "_actuator.h"
#include "_networkreceiver_43.h"
#include "_networkreceiver_71.h"
#include "_networkreceiver_99.h"
#include "_networkreceiver_127.h"
#include "__ap1_force.h"
#include "__ap2_force.h"
#include "__ap3_force.h"
#include "__ap4_force.h"
#include "_federate__a_main.h"
typedef enum {
    federate__a_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&envs[federate__a_main],"federate__a",federate__a_main,_lf_number_of_workers,0,0,0,0,8,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
#include "include/_federate__a_preamble.h"
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _federate__a_main_main_self_t* federate__a_main_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a_main_self);
    _actuator_self_t* federate__a_a_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a_a_self);
    _networkreceiver_43_self_t* federate__a_nr_federate__a_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a_nr_federate__a_self);
    _networkreceiver_71_self_t* federate__a_nr_federate__a_0_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a_nr_federate__a_0_self);
    _networkreceiver_99_self_t* federate__a_nr_federate__a_1_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a_nr_federate__a_1_self);
    _networkreceiver_127_self_t* federate__a_nr_federate__a_2_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a_nr_federate__a_2_self);
    __ap1_force_self_t* federate__a__ap1_force0_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a__ap1_force0_self);
    __ap2_force_self_t* federate__a__ap2_force0_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a__ap2_force0_self);
    __ap3_force_self_t* federate__a__ap3_force0_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a__ap3_force0_self);
    __ap4_force_self_t* federate__a__ap4_force0_self[1];
    SUPPRESS_UNUSED_WARNING(federate__a__ap4_force0_self);
    // ***** Start initializing federate__a of class federate__a
    federate__a_main_self[0] = new__federate__a_main();
    federate__a_main_self[0]->base.environment = &envs[federate__a_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a.a of class actuator
        federate__a_a_self[0] = new__actuator();
        federate__a_a_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__a_a_self[0]->_lf_p1_force_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__a_a_self[0]->_lf_p2_force_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__a_a_self[0]->_lf_p3_force_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__a_a_self[0]->_lf_p4_force_width = -2;
    
        federate__a_a_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing federate__a.a
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a.nr_federate__a of class NetworkReceiver_43
        federate__a_nr_federate__a_self[0] = new__networkreceiver_43();
        federate__a_nr_federate__a_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__a_nr_federate__a_self[0]->_lf_msg_width = -2;
        // Initializing action federate__a.nr_federate__a.networkMessage
        federate__a_nr_federate__a_self[0]->_lf__networkMessage.offset = 0;
        federate__a_nr_federate__a_self[0]->_lf__networkMessage.period = -1;
        federate__a_nr_federate__a_self[0]->_lf__networkMessage.last_tag = NEVER_TAG;
        federate__a_nr_federate__a_self[0]->_lf__networkMessage.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(federate__a_nr_federate__a_self[0]->_lf__networkMessage),
        sizeof(double));
        federate__a_nr_federate__a_self[0]->_lf__networkMessage.status = absent;
        federate__a_nr_federate__a_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing federate__a.nr_federate__a
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a.nr_federate__a_0 of class NetworkReceiver_71
        federate__a_nr_federate__a_0_self[0] = new__networkreceiver_71();
        federate__a_nr_federate__a_0_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__a_nr_federate__a_0_self[0]->_lf_msg_width = -2;
        // Initializing action federate__a.nr_federate__a_0.networkMessage
        federate__a_nr_federate__a_0_self[0]->_lf__networkMessage.offset = 0;
        federate__a_nr_federate__a_0_self[0]->_lf__networkMessage.period = -1;
        federate__a_nr_federate__a_0_self[0]->_lf__networkMessage.last_tag = NEVER_TAG;
        federate__a_nr_federate__a_0_self[0]->_lf__networkMessage.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(federate__a_nr_federate__a_0_self[0]->_lf__networkMessage),
        sizeof(double));
        federate__a_nr_federate__a_0_self[0]->_lf__networkMessage.status = absent;
        federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing federate__a.nr_federate__a_0
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a.nr_federate__a_1 of class NetworkReceiver_99
        federate__a_nr_federate__a_1_self[0] = new__networkreceiver_99();
        federate__a_nr_federate__a_1_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__a_nr_federate__a_1_self[0]->_lf_msg_width = -2;
        // Initializing action federate__a.nr_federate__a_1.networkMessage
        federate__a_nr_federate__a_1_self[0]->_lf__networkMessage.offset = 0;
        federate__a_nr_federate__a_1_self[0]->_lf__networkMessage.period = -1;
        federate__a_nr_federate__a_1_self[0]->_lf__networkMessage.last_tag = NEVER_TAG;
        federate__a_nr_federate__a_1_self[0]->_lf__networkMessage.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(federate__a_nr_federate__a_1_self[0]->_lf__networkMessage),
        sizeof(double));
        federate__a_nr_federate__a_1_self[0]->_lf__networkMessage.status = absent;
        federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing federate__a.nr_federate__a_1
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a.nr_federate__a_2 of class NetworkReceiver_127
        federate__a_nr_federate__a_2_self[0] = new__networkreceiver_127();
        federate__a_nr_federate__a_2_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__a_nr_federate__a_2_self[0]->_lf_msg_width = -2;
        // Initializing action federate__a.nr_federate__a_2.networkMessage
        federate__a_nr_federate__a_2_self[0]->_lf__networkMessage.offset = 0;
        federate__a_nr_federate__a_2_self[0]->_lf__networkMessage.period = -1;
        federate__a_nr_federate__a_2_self[0]->_lf__networkMessage.last_tag = NEVER_TAG;
        federate__a_nr_federate__a_2_self[0]->_lf__networkMessage.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(federate__a_nr_federate__a_2_self[0]->_lf__networkMessage),
        sizeof(double));
        federate__a_nr_federate__a_2_self[0]->_lf__networkMessage.status = absent;
        federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing federate__a.nr_federate__a_2
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a._ap1_force0 of class _ap1_force
        federate__a__ap1_force0_self[0] = new___ap1_force();
        federate__a__ap1_force0_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        federate__a__ap1_force0_self[0]->_lf_port_width = 1;
        // Allocate memory for multiport output.
        federate__a__ap1_force0_self[0]->_lf_port = (__ap1_force_port_t*)lf_allocate(
                1, sizeof(__ap1_force_port_t),
                &federate__a__ap1_force0_self[0]->base.allocations); 
        federate__a__ap1_force0_self[0]->_lf_port_pointers = (__ap1_force_port_t**)lf_allocate(
                1, sizeof(__ap1_force_port_t*),
                &federate__a__ap1_force0_self[0]->base.allocations); 
        // Assign each output port pointer to be used in
        // reactions to facilitate user access to output ports
        for(int i=0; i < 1; i++) {
                federate__a__ap1_force0_self[0]->_lf_port_pointers[i] = &(federate__a__ap1_force0_self[0]->_lf_port[i]);
        }
        // width of -2 indicates that it is not a multiport.
        federate__a__ap1_force0_self[0]->_lf_port0_width = -2;
    
        //***** End initializing federate__a._ap1_force0
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a._ap2_force0 of class _ap2_force
        federate__a__ap2_force0_self[0] = new___ap2_force();
        federate__a__ap2_force0_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        federate__a__ap2_force0_self[0]->_lf_port_width = 1;
        // Allocate memory for multiport output.
        federate__a__ap2_force0_self[0]->_lf_port = (__ap2_force_port_t*)lf_allocate(
                1, sizeof(__ap2_force_port_t),
                &federate__a__ap2_force0_self[0]->base.allocations); 
        federate__a__ap2_force0_self[0]->_lf_port_pointers = (__ap2_force_port_t**)lf_allocate(
                1, sizeof(__ap2_force_port_t*),
                &federate__a__ap2_force0_self[0]->base.allocations); 
        // Assign each output port pointer to be used in
        // reactions to facilitate user access to output ports
        for(int i=0; i < 1; i++) {
                federate__a__ap2_force0_self[0]->_lf_port_pointers[i] = &(federate__a__ap2_force0_self[0]->_lf_port[i]);
        }
        // width of -2 indicates that it is not a multiport.
        federate__a__ap2_force0_self[0]->_lf_port0_width = -2;
    
        //***** End initializing federate__a._ap2_force0
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a._ap3_force0 of class _ap3_force
        federate__a__ap3_force0_self[0] = new___ap3_force();
        federate__a__ap3_force0_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        federate__a__ap3_force0_self[0]->_lf_port_width = 1;
        // Allocate memory for multiport output.
        federate__a__ap3_force0_self[0]->_lf_port = (__ap3_force_port_t*)lf_allocate(
                1, sizeof(__ap3_force_port_t),
                &federate__a__ap3_force0_self[0]->base.allocations); 
        federate__a__ap3_force0_self[0]->_lf_port_pointers = (__ap3_force_port_t**)lf_allocate(
                1, sizeof(__ap3_force_port_t*),
                &federate__a__ap3_force0_self[0]->base.allocations); 
        // Assign each output port pointer to be used in
        // reactions to facilitate user access to output ports
        for(int i=0; i < 1; i++) {
                federate__a__ap3_force0_self[0]->_lf_port_pointers[i] = &(federate__a__ap3_force0_self[0]->_lf_port[i]);
        }
        // width of -2 indicates that it is not a multiport.
        federate__a__ap3_force0_self[0]->_lf_port0_width = -2;
    
        //***** End initializing federate__a._ap3_force0
    }
    {
        _federate__a_main_main_self_t *self = federate__a_main_self[0];
        // ***** Start initializing federate__a._ap4_force0 of class _ap4_force
        federate__a__ap4_force0_self[0] = new___ap4_force();
        federate__a__ap4_force0_self[0]->base.environment = &envs[federate__a_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        federate__a__ap4_force0_self[0]->_lf_port_width = 1;
        // Allocate memory for multiport output.
        federate__a__ap4_force0_self[0]->_lf_port = (__ap4_force_port_t*)lf_allocate(
                1, sizeof(__ap4_force_port_t),
                &federate__a__ap4_force0_self[0]->base.allocations); 
        federate__a__ap4_force0_self[0]->_lf_port_pointers = (__ap4_force_port_t**)lf_allocate(
                1, sizeof(__ap4_force_port_t*),
                &federate__a__ap4_force0_self[0]->base.allocations); 
        // Assign each output port pointer to be used in
        // reactions to facilitate user access to output ports
        for(int i=0; i < 1; i++) {
                federate__a__ap4_force0_self[0]->_lf_port_pointers[i] = &(federate__a__ap4_force0_self[0]->_lf_port[i]);
        }
        // width of -2 indicates that it is not a multiport.
        federate__a__ap4_force0_self[0]->_lf_port0_width = -2;
    
        //***** End initializing federate__a._ap4_force0
    }
    //***** End initializing federate__a
    // **** Start deferred initialize for federate__a
    {
        federate__a_main_self[0]->base.name = "federate__a";
        federate__a_main_self[0]->base.parent = (self_base_t*)NULL;
    
    
    
        // **** Start deferred initialize for federate__a.a
        {
            federate__a_a_self[0]->base.name = "a";
            federate__a_a_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
            federate__a_a_self[0]->_lf__reaction_0.name = "federate__a.a reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__a.a.
            federate__a_a_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of federate__a.a
        
        }
        // **** End of deferred initialize for federate__a.a
        // **** Start deferred initialize for federate__a.nr_federate__a
        {
            federate__a_nr_federate__a_self[0]->base.name = "nr_federate__a";
            federate__a_nr_federate__a_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
            federate__a_nr_federate__a_self[0]->_lf__reaction_0.name = "federate__a.nr_federate__a reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__a.nr_federate__a.
            federate__a_nr_federate__a_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__a_nr_federate__a_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__a_nr_federate__a_self[0]->base.allocations);
            federate__a_nr_federate__a_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &federate__a_nr_federate__a_self[0]->base.allocations);
            federate__a_nr_federate__a_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &federate__a_nr_federate__a_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__a_nr_federate__a_self[0]->_lf__reaction_0.output_produced[count++] = &federate__a_nr_federate__a_self[0]->_lf_msg.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of federate__a.nr_federate__a
        
        }
        // **** End of deferred initialize for federate__a.nr_federate__a
        // **** Start deferred initialize for federate__a.nr_federate__a_0
        {
            federate__a_nr_federate__a_0_self[0]->base.name = "nr_federate__a_0";
            federate__a_nr_federate__a_0_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
            federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.name = "federate__a.nr_federate__a_0 reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__a.nr_federate__a_0.
            federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__a_nr_federate__a_0_self[0]->base.allocations);
            federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &federate__a_nr_federate__a_0_self[0]->base.allocations);
            federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &federate__a_nr_federate__a_0_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.output_produced[count++] = &federate__a_nr_federate__a_0_self[0]->_lf_msg.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of federate__a.nr_federate__a_0
        
        }
        // **** End of deferred initialize for federate__a.nr_federate__a_0
        // **** Start deferred initialize for federate__a.nr_federate__a_1
        {
            federate__a_nr_federate__a_1_self[0]->base.name = "nr_federate__a_1";
            federate__a_nr_federate__a_1_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
            federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.name = "federate__a.nr_federate__a_1 reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__a.nr_federate__a_1.
            federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__a_nr_federate__a_1_self[0]->base.allocations);
            federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &federate__a_nr_federate__a_1_self[0]->base.allocations);
            federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &federate__a_nr_federate__a_1_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.output_produced[count++] = &federate__a_nr_federate__a_1_self[0]->_lf_msg.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of federate__a.nr_federate__a_1
        
        }
        // **** End of deferred initialize for federate__a.nr_federate__a_1
        // **** Start deferred initialize for federate__a.nr_federate__a_2
        {
            federate__a_nr_federate__a_2_self[0]->base.name = "nr_federate__a_2";
            federate__a_nr_federate__a_2_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
            federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.name = "federate__a.nr_federate__a_2 reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__a.nr_federate__a_2.
            federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__a_nr_federate__a_2_self[0]->base.allocations);
            federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &federate__a_nr_federate__a_2_self[0]->base.allocations);
            federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &federate__a_nr_federate__a_2_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.output_produced[count++] = &federate__a_nr_federate__a_2_self[0]->_lf_msg.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of federate__a.nr_federate__a_2
        
        }
        // **** End of deferred initialize for federate__a.nr_federate__a_2
        // **** Start deferred initialize for federate__a._ap1_force0
        {
            federate__a__ap1_force0_self[0]->base.name = "_ap1_force0";
            federate__a__ap1_force0_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
        
        
        }
        // **** End of deferred initialize for federate__a._ap1_force0
        // **** Start deferred initialize for federate__a._ap2_force0
        {
            federate__a__ap2_force0_self[0]->base.name = "_ap2_force0";
            federate__a__ap2_force0_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
        
        
        }
        // **** End of deferred initialize for federate__a._ap2_force0
        // **** Start deferred initialize for federate__a._ap3_force0
        {
            federate__a__ap3_force0_self[0]->base.name = "_ap3_force0";
            federate__a__ap3_force0_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
        
        
        }
        // **** End of deferred initialize for federate__a._ap3_force0
        // **** Start deferred initialize for federate__a._ap4_force0
        {
            federate__a__ap4_force0_self[0]->base.name = "_ap4_force0";
            federate__a__ap4_force0_self[0]->base.parent = (self_base_t*)federate__a_main_self[0];
        
        
        
        }
        // **** End of deferred initialize for federate__a._ap4_force0
    }
    // **** End of deferred initialize for federate__a
    // **** Start non-nested deferred initialize for federate__a
    {
    
    
    
        // **** Start non-nested deferred initialize for federate__a.a
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for federate__a.a
        // **** Start non-nested deferred initialize for federate__a.nr_federate__a
        {
        
            // For reference counting, set num_destinations for port federate__a.nr_federate__a.msg.
            // Iterate over range federate__a.nr_federate__a.msg(0,1)->[federate__a.a.p1_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a_nr_federate__a_self[src_runtime]->_lf_msg._base.num_destinations = 1;
                federate__a_nr_federate__a_self[src_runtime]->_lf_msg._base.source_reactor = (self_base_t*)federate__a_nr_federate__a_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range federate__a.nr_federate__a.msg(0,1)->[federate__a.a.p1_force(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of federate__a.nr_federate__a triggers 1 downstream reactions
                    // through port federate__a.nr_federate__a.msg.
                    federate__a_nr_federate__a_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of federate__a.nr_federate__a, allocate an
                    // array of trigger pointers for downstream reactions through port federate__a.nr_federate__a.msg
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &federate__a_nr_federate__a_self[src_runtime]->base.allocations); 
                    federate__a_nr_federate__a_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges federate__a.nr_federate__a.msg(0,1)->[federate__a.a.p1_force(0,1)] and federate__a.a.p1_force(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range federate__a.a.p1_force(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port federate__a.a.p1_force's trigger struct.
                        federate__a_nr_federate__a_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__a_a_self[dst_runtime]->_lf__p1_force;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for federate__a.nr_federate__a
        // **** Start non-nested deferred initialize for federate__a.nr_federate__a_0
        {
        
            // For reference counting, set num_destinations for port federate__a.nr_federate__a_0.msg.
            // Iterate over range federate__a.nr_federate__a_0.msg(0,1)->[federate__a.a.p2_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a_nr_federate__a_0_self[src_runtime]->_lf_msg._base.num_destinations = 1;
                federate__a_nr_federate__a_0_self[src_runtime]->_lf_msg._base.source_reactor = (self_base_t*)federate__a_nr_federate__a_0_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range federate__a.nr_federate__a_0.msg(0,1)->[federate__a.a.p2_force(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of federate__a.nr_federate__a_0 triggers 1 downstream reactions
                    // through port federate__a.nr_federate__a_0.msg.
                    federate__a_nr_federate__a_0_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of federate__a.nr_federate__a_0, allocate an
                    // array of trigger pointers for downstream reactions through port federate__a.nr_federate__a_0.msg
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &federate__a_nr_federate__a_0_self[src_runtime]->base.allocations); 
                    federate__a_nr_federate__a_0_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges federate__a.nr_federate__a_0.msg(0,1)->[federate__a.a.p2_force(0,1)] and federate__a.a.p2_force(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range federate__a.a.p2_force(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port federate__a.a.p2_force's trigger struct.
                        federate__a_nr_federate__a_0_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__a_a_self[dst_runtime]->_lf__p2_force;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for federate__a.nr_federate__a_0
        // **** Start non-nested deferred initialize for federate__a.nr_federate__a_1
        {
        
            // For reference counting, set num_destinations for port federate__a.nr_federate__a_1.msg.
            // Iterate over range federate__a.nr_federate__a_1.msg(0,1)->[federate__a.a.p3_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a_nr_federate__a_1_self[src_runtime]->_lf_msg._base.num_destinations = 1;
                federate__a_nr_federate__a_1_self[src_runtime]->_lf_msg._base.source_reactor = (self_base_t*)federate__a_nr_federate__a_1_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range federate__a.nr_federate__a_1.msg(0,1)->[federate__a.a.p3_force(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of federate__a.nr_federate__a_1 triggers 1 downstream reactions
                    // through port federate__a.nr_federate__a_1.msg.
                    federate__a_nr_federate__a_1_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of federate__a.nr_federate__a_1, allocate an
                    // array of trigger pointers for downstream reactions through port federate__a.nr_federate__a_1.msg
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &federate__a_nr_federate__a_1_self[src_runtime]->base.allocations); 
                    federate__a_nr_federate__a_1_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges federate__a.nr_federate__a_1.msg(0,1)->[federate__a.a.p3_force(0,1)] and federate__a.a.p3_force(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range federate__a.a.p3_force(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port federate__a.a.p3_force's trigger struct.
                        federate__a_nr_federate__a_1_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__a_a_self[dst_runtime]->_lf__p3_force;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for federate__a.nr_federate__a_1
        // **** Start non-nested deferred initialize for federate__a.nr_federate__a_2
        {
        
            // For reference counting, set num_destinations for port federate__a.nr_federate__a_2.msg.
            // Iterate over range federate__a.nr_federate__a_2.msg(0,1)->[federate__a.a.p4_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a_nr_federate__a_2_self[src_runtime]->_lf_msg._base.num_destinations = 1;
                federate__a_nr_federate__a_2_self[src_runtime]->_lf_msg._base.source_reactor = (self_base_t*)federate__a_nr_federate__a_2_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range federate__a.nr_federate__a_2.msg(0,1)->[federate__a.a.p4_force(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of federate__a.nr_federate__a_2 triggers 1 downstream reactions
                    // through port federate__a.nr_federate__a_2.msg.
                    federate__a_nr_federate__a_2_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of federate__a.nr_federate__a_2, allocate an
                    // array of trigger pointers for downstream reactions through port federate__a.nr_federate__a_2.msg
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &federate__a_nr_federate__a_2_self[src_runtime]->base.allocations); 
                    federate__a_nr_federate__a_2_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges federate__a.nr_federate__a_2.msg(0,1)->[federate__a.a.p4_force(0,1)] and federate__a.a.p4_force(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range federate__a.a.p4_force(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port federate__a.a.p4_force's trigger struct.
                        federate__a_nr_federate__a_2_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__a_a_self[dst_runtime]->_lf__p4_force;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for federate__a.nr_federate__a_2
        // **** Start non-nested deferred initialize for federate__a._ap1_force0
        {
        
            // For reference counting, set num_destinations for port federate__a._ap1_force0.port.
            // Iterate over range federate__a._ap1_force0.port(0,1)->[federate__a.a.p1_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a__ap1_force0_self[src_runtime]->_lf_port[src_channel]._base.num_destinations = 1;
                federate__a__ap1_force0_self[src_runtime]->_lf_port[src_channel]._base.source_reactor = (self_base_t*)federate__a__ap1_force0_self[src_runtime];
            }
        
        
        }
        // **** End of non-nested deferred initialize for federate__a._ap1_force0
        // **** Start non-nested deferred initialize for federate__a._ap2_force0
        {
        
            // For reference counting, set num_destinations for port federate__a._ap2_force0.port.
            // Iterate over range federate__a._ap2_force0.port(0,1)->[federate__a.a.p2_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a__ap2_force0_self[src_runtime]->_lf_port[src_channel]._base.num_destinations = 1;
                federate__a__ap2_force0_self[src_runtime]->_lf_port[src_channel]._base.source_reactor = (self_base_t*)federate__a__ap2_force0_self[src_runtime];
            }
        
        
        }
        // **** End of non-nested deferred initialize for federate__a._ap2_force0
        // **** Start non-nested deferred initialize for federate__a._ap3_force0
        {
        
            // For reference counting, set num_destinations for port federate__a._ap3_force0.port.
            // Iterate over range federate__a._ap3_force0.port(0,1)->[federate__a.a.p3_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a__ap3_force0_self[src_runtime]->_lf_port[src_channel]._base.num_destinations = 1;
                federate__a__ap3_force0_self[src_runtime]->_lf_port[src_channel]._base.source_reactor = (self_base_t*)federate__a__ap3_force0_self[src_runtime];
            }
        
        
        }
        // **** End of non-nested deferred initialize for federate__a._ap3_force0
        // **** Start non-nested deferred initialize for federate__a._ap4_force0
        {
        
            // For reference counting, set num_destinations for port federate__a._ap4_force0.port.
            // Iterate over range federate__a._ap4_force0.port(0,1)->[federate__a.a.p4_force(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                federate__a__ap4_force0_self[src_runtime]->_lf_port[src_channel]._base.num_destinations = 1;
                federate__a__ap4_force0_self[src_runtime]->_lf_port[src_channel]._base.source_reactor = (self_base_t*)federate__a__ap4_force0_self[src_runtime];
            }
        
        
        }
        // **** End of non-nested deferred initialize for federate__a._ap4_force0
    }
    // **** End of non-nested deferred initialize for federate__a
    // Connect inputs and outputs for reactor federate__a.
    // Connect inputs and outputs for reactor federate__a.a.
    // Connect inputs and outputs for reactor federate__a.nr_federate__a.
    // Connect federate__a.nr_federate__a.msg(0,1)->[federate__a.a.p1_force(0,1)] to port federate__a.a.p1_force(0,1)
    // Iterate over ranges federate__a.nr_federate__a.msg(0,1)->[federate__a.a.p1_force(0,1)] and federate__a.a.p1_force(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__a.a.p1_force(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__a_a_self[dst_runtime]->_lf_p1_force = (_actuator_p1_force_t*)&federate__a_nr_federate__a_self[src_runtime]->_lf_msg;
        }
    }
    // Connect inputs and outputs for reactor federate__a.nr_federate__a_0.
    // Connect federate__a.nr_federate__a_0.msg(0,1)->[federate__a.a.p2_force(0,1)] to port federate__a.a.p2_force(0,1)
    // Iterate over ranges federate__a.nr_federate__a_0.msg(0,1)->[federate__a.a.p2_force(0,1)] and federate__a.a.p2_force(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__a.a.p2_force(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__a_a_self[dst_runtime]->_lf_p2_force = (_actuator_p2_force_t*)&federate__a_nr_federate__a_0_self[src_runtime]->_lf_msg;
        }
    }
    // Connect inputs and outputs for reactor federate__a.nr_federate__a_1.
    // Connect federate__a.nr_federate__a_1.msg(0,1)->[federate__a.a.p3_force(0,1)] to port federate__a.a.p3_force(0,1)
    // Iterate over ranges federate__a.nr_federate__a_1.msg(0,1)->[federate__a.a.p3_force(0,1)] and federate__a.a.p3_force(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__a.a.p3_force(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__a_a_self[dst_runtime]->_lf_p3_force = (_actuator_p3_force_t*)&federate__a_nr_federate__a_1_self[src_runtime]->_lf_msg;
        }
    }
    // Connect inputs and outputs for reactor federate__a.nr_federate__a_2.
    // Connect federate__a.nr_federate__a_2.msg(0,1)->[federate__a.a.p4_force(0,1)] to port federate__a.a.p4_force(0,1)
    // Iterate over ranges federate__a.nr_federate__a_2.msg(0,1)->[federate__a.a.p4_force(0,1)] and federate__a.a.p4_force(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__a.a.p4_force(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__a_a_self[dst_runtime]->_lf_p4_force = (_actuator_p4_force_t*)&federate__a_nr_federate__a_2_self[src_runtime]->_lf_msg;
        }
    }
    // Connect inputs and outputs for reactor federate__a._ap1_force0.
    // Connect inputs and outputs for reactor federate__a._ap2_force0.
    // Connect inputs and outputs for reactor federate__a._ap3_force0.
    // Connect inputs and outputs for reactor federate__a._ap4_force0.
    {
    }
    {
        // Add action federate__a.nr_federate__a.networkMessage to array of is_present fields.
        envs[federate__a_main].is_present_fields[0 + (0) * 1]
                = (bool *) &federate__a_nr_federate__a_self[0]->_lf__networkMessage.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action federate__a.nr_federate__a.networkMessage to array of intended_tag fields.
        envs[federate__a_main]._lf_intended_tag_fields[0 + (0) * 1]
                = &federate__a_nr_federate__a_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action federate__a.nr_federate__a_0.networkMessage to array of is_present fields.
        envs[federate__a_main].is_present_fields[1 + (0) * 1]
                = (bool *) &federate__a_nr_federate__a_0_self[0]->_lf__networkMessage.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action federate__a.nr_federate__a_0.networkMessage to array of intended_tag fields.
        envs[federate__a_main]._lf_intended_tag_fields[1 + (0) * 1]
                = &federate__a_nr_federate__a_0_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action federate__a.nr_federate__a_1.networkMessage to array of is_present fields.
        envs[federate__a_main].is_present_fields[2 + (0) * 1]
                = (bool *) &federate__a_nr_federate__a_1_self[0]->_lf__networkMessage.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action federate__a.nr_federate__a_1.networkMessage to array of intended_tag fields.
        envs[federate__a_main]._lf_intended_tag_fields[2 + (0) * 1]
                = &federate__a_nr_federate__a_1_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action federate__a.nr_federate__a_2.networkMessage to array of is_present fields.
        envs[federate__a_main].is_present_fields[3 + (0) * 1]
                = (bool *) &federate__a_nr_federate__a_2_self[0]->_lf__networkMessage.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action federate__a.nr_federate__a_2.networkMessage to array of intended_tag fields.
        envs[federate__a_main]._lf_intended_tag_fields[3 + (0) * 1]
                = &federate__a_nr_federate__a_2_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
    }
    {
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port federate__a.nr_federate__a.msg to array of is_present fields.
            envs[federate__a_main].is_present_fields[(0) * 1 + 4 + count] = &federate__a_nr_federate__a_self[0]->_lf_msg.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port federate__a.nr_federate__a.msg to array of intended_tag fields.
            envs[federate__a_main]._lf_intended_tag_fields[(0) * 1 + 4 + count] = &federate__a_nr_federate__a_self[0]->_lf_msg.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port federate__a.nr_federate__a_0.msg to array of is_present fields.
            envs[federate__a_main].is_present_fields[(0) * 1 + 5 + count] = &federate__a_nr_federate__a_0_self[0]->_lf_msg.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port federate__a.nr_federate__a_0.msg to array of intended_tag fields.
            envs[federate__a_main]._lf_intended_tag_fields[(0) * 1 + 5 + count] = &federate__a_nr_federate__a_0_self[0]->_lf_msg.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port federate__a.nr_federate__a_1.msg to array of is_present fields.
            envs[federate__a_main].is_present_fields[(0) * 1 + 6 + count] = &federate__a_nr_federate__a_1_self[0]->_lf_msg.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port federate__a.nr_federate__a_1.msg to array of intended_tag fields.
            envs[federate__a_main]._lf_intended_tag_fields[(0) * 1 + 6 + count] = &federate__a_nr_federate__a_1_self[0]->_lf_msg.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port federate__a.nr_federate__a_2.msg to array of is_present fields.
            envs[federate__a_main].is_present_fields[(0) * 1 + 7 + count] = &federate__a_nr_federate__a_2_self[0]->_lf_msg.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port federate__a.nr_federate__a_2.msg to array of intended_tag fields.
            envs[federate__a_main]._lf_intended_tag_fields[(0) * 1 + 7 + count] = &federate__a_nr_federate__a_2_self[0]->_lf_msg.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    
    // Set reaction priorities for ReactorInstance federate__a
    {
    
        // Set reaction priorities for ReactorInstance federate__a.a
        {
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__a_a_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 1);
        }
    
    
        // Set reaction priorities for ReactorInstance federate__a.nr_federate__a
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__a_nr_federate__a_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance federate__a.nr_federate__a_0
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__a_nr_federate__a_0_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance federate__a.nr_federate__a_1
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__a_nr_federate__a_1_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance federate__a.nr_federate__a_2
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__a_nr_federate__a_2_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[2] = 
        {4, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 2};
    lf_sched_init(
        &envs[federate__a_main],
        envs[federate__a_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
